### ISSUE TITLE
IOS - getting "receiveNotification: notification discarted" if i send notification from FCM

### ISSUE THREAD

**Issue by bysano** [rafaelsetragni/awesome_notifications#41]
notofocation example
```
{
    "mutable_content": true,
    "notification": {
        "title": " "
    },
    "data": {
        "content": {
            "id": 100,
            "channelKey": "big_picture",
            "title": "Huston!\nThe eagle has landed!",
            "body": "A small step for a man, but a giant leap to Flutter's community!",
            "notificationLayout": "BigPicture",
            "bigPicture": "https://www.dw.com/image/49519617_303.jpg",
            "showWhen": true,
            "autoCancel": true,
            "privacy": "Private",
            "payload": {
                "actions": "[{\"actionKey\": \"REDIRECT\",\"actionValue\": \"https://www.google.com/\"},{\"actionKey\": \"DISMISS\",\"actionValue\": null}]"
            }
        },
        "actionButtons": [
            {
                "key": "REDIRECT",
                "label": "Redirect",
                "autoCancel": true
            },
            {
                "key": "DISMISS",
                "label": "Dismiss",
                "autoCancel": true
            }
        ]
    },
    "to": "eZ0dsST_qUJqo-O82IUR27:APA91bGwwEP1OiZ_Gm1520n2va7CpzVCTBfl7OURXvvw7hktKZ4oB9hxeH-lIbtge2rvvD1600mzSy8lwd37PKZvPK7OSteVRAf2FRpz9FyZfeKM54i_2ASK_KcR822N0Zl-HALUBSa6"
}
```

i've sopped in debug in SwiftAwesomeNotificationPlugin.swift
line 255 let jsonData:String? = nil
![image](https://user-images.githubusercontent.com/24550731/99806266-d53e3780-2b4e-11eb-8a86-7bb9c9dcca08.png)

**Comment by bysano** [comment]
and if app collapsed notifications appears empty 
![photo_2020-11-20_16-50-45](https://user-images.githubusercontent.com/24550731/99807683-e8ea9d80-2b50-11eb-9e09-f671a22e9e34.jpg)

**Comment by rafaelsetragni** [comment]
The empty notification is resulted when AwesomeServiceExtension is not getting called. This empty notification is fired by firebase default FCM system when the app is in background or closed.

Check if the AwesomeServiceExtension target is getting called attaching XCode to the process in "Debug > Attatch to process by PID or Name".

![image](https://user-images.githubusercontent.com/40064496/99816807-e37a5c80-2b2a-11eb-8dcf-d3b41fc956b1.png)

**Comment by bysano** [comment]
Thanks for Answer!

**Comment by rafaelsetragni** [comment]
If the service does not wake up and do not get called, the attatch process will keep waiting forever. Sometimes the target extension is not wake up imediately after your app goes up, but instead when a new push notification arives. Put a break point on the first instruction inside didReceive method from AwesomeServiceExtension class:

https://github.com/rafaelsetragni/awesome_notifications/blob/0a0ac6a16036d2d4c1ae5e2764b64a38efbfa7fb/ios/Classes/lib/Services/AwesomeServiceExtension.swift#L21

If even in this cases the service extension is not beeing called, so theres something missing on your project configuration to activate your notification service extension.

**Comment by bysano** [comment]
i've Found solution for my problem
 if select deploymentInfo for Notification service extension - IOS 10 instead of 14 , works fine
![image](https://user-images.githubusercontent.com/24550731/99852751-afd31d00-2b92-11eb-86e2-857ff257d778.png)

**Comment by bysano** [comment]
But, is it expected behavior that i don't see action buttons in notification ?
![image](https://user-images.githubusercontent.com/24550731/99853018-3e479e80-2b93-11eb-8c9f-52854c610220.png)

**Comment by rafaelsetragni** [comment]
Check for me if you action buttons work on local notifications.

**Comment by bysano** [comment]
when i create notification insight application as described here https://github.com/rafaelsetragni/awesome_notifications/issues/27 action buttons works fine

**Comment by bysano** [comment]
found causes this issue -
AwesomeServiceExtension line 62

     mapData[Definitions.PUSH_NOTIFICATION_BUTTONS]  = JsonUtils.fromJson(content.userInfo[Definitions.PUSH_NOTIFICATION_BUTTONS] as? String) returns nil 
because content.userInfo[Definitions.PUSH_NOTIFICATION_BUTTONS] is Array

**Comment by rafaelsetragni** [comment]
Outstanding!

You are absolutely right! Your method is able to extract the button content from the json package.
Do you want to fork this project and send me back the pull request with your fix? Your name will be registered as a project contributor.

**Comment by bysano** [comment]
Ok! I'll create pull request

**Comment by bysano** [comment]
Done!
https://github.com/rafaelsetragni/awesome_notifications/pull/43/files
maybe it would be fine,  to mention in readme  problem with notification  service targets which i faced, it can help someone =)

**Comment by rafaelsetragni** [comment]
About iOS 10 version? Yes ill include that information on README file.

**Comment by bysano** [comment]
Yes! Thanks for your work ! This plugin is really usefull!

**Comment by efraespada** [comment]
> and if app collapsed notifications appears empty
> ![photo_2020-11-20_16-50-45](https://user-images.githubusercontent.com/24550731/99807683-e8ea9d80-2b50-11eb-9e09-f671a22e9e34.jpg)

I'm having the same problem. The deploy info is set to **10.0**. 🤔

**Comment by jwiesmann** [comment]
> If the service does not wake up and do not get called, the attatch process will keep waiting forever. Sometimes the target extension is not wake up imediately after your app goes up, but instead when a new push notification arives. Put a break point on the first instruction inside didReceive method from AwesomeServiceExtension class:
> 
> https://github.com/rafaelsetragni/awesome_notifications/blob/0a0ac6a16036d2d4c1ae5e2764b64a38efbfa7fb/ios/Classes/lib/Services/AwesomeServiceExtension.swift#L21
> 
> If even in this cases the service extension is not beeing called, so theres something missing on your project configuration to activate your notification service extension.

Hi, 

first of all thank you for this nice plugin! I am having some trouble making it work in IOS though. I am getting exactly the same error like @bysano and followed all tips from here, but i still cannot resolve it. 
Like you stated above, that this method should be called, it is not in my case and i am running out of ideas.

I created everything and even compared it with the settings from https://github.com/bayuramadeza/Awesome-Notification-FCM. The only difference so far is, that i do not have 
_AwesomeContentExtension.entitlements_ nor _AwesomeServiceExtension.entitlements_ in my project.

I am getting all kinds of infos, that it is initiated and so on and everything is running fine on android f.e.
`"Awesome Notifications - App Group : group.AwesomeNotifications.....`
`"AwesomeNotificationsPlugin: Awesome Notification service initialized"`

but whenever i receive a notification i am getting:
`"receiveNotification: notification discarted"` 

debuging shows that there is a message, but like you stated above, it is empty and 'didReceive method from AwesomeServiceExtension' is never called.

any ideas?

Thank you!

**Comment by rafaelsetragni** [comment]
Please jwiesmann, open a new topic with your issue. This will help me to organize the recent issues and fix then faster.

**Comment by jwiesmann** [comment]
> Please jwiesmann, open a new topic with your issue. This will help me to organize the recent issues and fix then faster.

Will do!

**Comment by arsalanj** [comment]
getting "receiveNotification: notification discarted" when sending via apns 
Should I open a new issue ? @rafaelsetragni

**Comment by MaheshPeri19** [comment]
For me also same issue. Some times firebase _firebaseMessaging.configure (onMessage()) when app foreground is calling, sometimes it is not calling. In iOS remaining mode terminated and background are not at all calling.

In android no issues found and perfectly working.

**Comment by MaheshPeri19** [comment]
Update : 

I have added "content_available": true, in my payload, then iOS app receiving push notifications. But in background mode, i am getting below fatal error in SwiftAwesomeNotificationsPlugin.swift file.

2021-01-25 19:11:20.791322+0530 Runner[909:278651] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file awesome_notifications/SwiftAwesomeNotificationsPlugin.swift, line 395

**Comment by whatamelon** [comment]
I have same issue 
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file awesome_notifications/SwiftAwesomeNotificationsPlugin.swift, line 395

So I changing code 
`if actionReceived?.dismissedDate == nil {`
instead of 
`if actionReceived!.dismissedDate == nil {`

then, any method does not implemented.

Anyone get solution?

**Comment by Zeeshan0201** [comment]
still facing the same issue, the iOS foreground app can not receive notifications. any updates on this guys?
